/** @type {import('tailwindcss').Config} */
const colors = {
  warmCanvas: '#fbfaf9',
  stoneSurface: '#f2f0ed',
  parchmentCard: '#f8f7f4',
  graphite: '#474645',
  charcoalPrimary: '#343433',
  midnight: '#121212',
  obsidian: '#000000',
  ash: '#848281',
  fog: '#c6c6c6',
  smoke: '#a7a7a7',
  pepper: '#282624',
  emberOrange: '#ff3e00',
  meadowGreen: '#00ca48',
  skyBlue: '#0090ff',
  sunburstYellow: '#ffbb26',
  deepAmber: '#d48f00',
  oceanBlue: '#0086fc',
  iceBlue: '#64c6ff',
  spearmint: '#00c978',
  flamingo: '#ff58ae',
  violetPop: '#9f4fff',
  coralRed: '#ff2b3a',
  validGreen: '#00c454',
};

module.exports = {
  content: [
    './app/**/*.{js,ts,tsx}',
    './components/**/*.{js,ts,tsx}',
    './constants/**/*.{js,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'warm-canvas': colors.warmCanvas,
        'stone-surface': colors.stoneSurface,
        'parchment-card': colors.parchmentCard,
        graphite: colors.graphite,
        'charcoal-primary': colors.charcoalPrimary,
        midnight: colors.midnight,
        obsidian: colors.obsidian,
        ash: colors.ash,
        fog: colors.fog,
        smoke: colors.smoke,
        pepper: colors.pepper,
        'ember-orange': colors.emberOrange,
        'meadow-green': colors.meadowGreen,
        'sky-blue': colors.skyBlue,
        'sunburst-yellow': colors.sunburstYellow,
        'deep-amber': colors.deepAmber,
        'ocean-blue': colors.oceanBlue,
        'ice-blue': colors.iceBlue,
        spearmint: colors.spearmint,
        flamingo: colors.flamingo,
        'violet-pop': colors.violetPop,
        'coral-red': colors.coralRed,
        'valid-green': colors.validGreen,
        primary: {
          DEFAULT: colors.emberOrange,
          accent: colors.emberOrange,
          dark: '#db3500',
          secondary: colors.meadowGreen,
          tertiary: colors.sunburstYellow,
        },
        background: {
          DEFAULT: colors.warmCanvas,
          main: colors.warmCanvas,
          surface: colors.stoneSurface,
          card: colors.parchmentCard,
          inverse: colors.midnight,
        },
        surface: colors.stoneSurface,
        card: colors.parchmentCard,
        text: {
          primary: colors.charcoalPrimary,
          secondary: colors.ash,
          tertiary: colors.smoke,
          muted: colors.graphite,
          inverse: colors.warmCanvas,
        },
        success: colors.meadowGreen,
        destructive: colors.coralRed,
        error: colors.coralRed,
        warning: colors.sunburstYellow,
        info: colors.skyBlue,
        overlay: 'rgba(18, 18, 18, 0.64)',
        // Dark mode palette
        dark: {
          bg: '#0a0a0a',
          surface: '#050505',
          'surface-elevated': colors.graphite,
          text: colors.warmCanvas,
          'text-secondary': colors.fog,
          separator: colors.graphite,
        },
      },
      fontFamily: {
        sans: ['Geist-Regular'],
        display: ['Geist-Bold'],
        heading: ['Geist-Bold'],
        'heading-bold': ['Geist-Bold'],
        'heading-semibold': ['Geist-SemiBold'],
        headline: ['Geist-Bold'],
        'headline-1': ['Geist-Bold'],
        'headline-2': ['Geist-SemiBold'],
        subtitle: ['Geist-SemiBold'],
        body: ['Geist-Regular'],
        'body-medium': ['Geist-Medium'],
        'body-bold': ['Geist-Bold'],
        caption: ['Geist-Regular'],
        button: ['Geist-SemiBold'],
        numeric: ['Geist-Medium'],
        mono: ['Geist-Regular'],
        'mono-medium': ['Geist-Medium'],
        'mono-semibold': ['Geist-SemiBold'],
        'mono-bold': ['Geist-Bold'],
        thin: ['Geist-Thin'],
        extralight: ['Geist-ExtraLight'],
        light: ['Geist-Light'],
        black: ['Geist-Black'],
      },
      fontSize: {
        display: ['68px', { lineHeight: '1.09' }],
        'display-lg': ['48px', { lineHeight: '1.1' }],
        'heading-lg': ['44px', { lineHeight: '1.09' }],
        heading: ['23px', { lineHeight: '1.2' }],
        'heading-sm': ['19px', { lineHeight: '1.38' }],
        'headline-1': ['32px', { lineHeight: '1.2' }],
        'headline-2': ['24px', { lineHeight: '1.3' }],
        'headline-3': ['20px', { lineHeight: '1.3' }],
        subtitle: ['18px', { lineHeight: '1.4' }],
        body: ['15px', { lineHeight: '1.47' }],
        'body-lg': ['16px', { lineHeight: '1.5' }],
        caption: ['12px', { lineHeight: '1.58' }],
        small: ['12px', { lineHeight: '1.5' }],
        'button-lg': ['18px', { lineHeight: '1.1' }],
        // Named sizes for previously hardcoded values
        'balance-lg': ['50px', { lineHeight: '1.1' }],
        'balance-sm': ['32px', { lineHeight: '1.1' }],
        'auth-title': ['40px', { lineHeight: '1.1' }],
        keypad: ['30px', { lineHeight: '1.2' }],
        stash: ['26px', { lineHeight: '1.2' }],
      },
      spacing: {
        'rail-4': '4px',
        'rail-8': '8px',
        'rail-12': '12px',
        'rail-16': '16px',
        'rail-20': '20px',
        'rail-24': '24px',
        'rail-28': '28px',
        'rail-32': '32px',
        'rail-36': '36px',
        'rail-48': '48px',
        'rail-60': '60px',
        'rail-76': '76px',
        'rail-80': '80px',
        'rail-92': '92px',
        'rail-96': '96px',
        'rail-104': '104px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
      },
      borderRadius: {
        sm: '2px',
        md: '6px',
        lg: '10px',
        '2xl': '17px',
        '3xl': '24px',
        '3xl-2': '32px',
        '3xl-3': '40px',
        full: '72px',
      },
      height: {
        keypad: '72px',
        input: '52px',
        'pin-dot': '56px',
      },
      boxShadow: {
        subtle: 'inset 0 0 0 1px #f7f2e8',
        'subtle-2': 'inset 0 0 0 0 #f7f2e8',
        'subtle-3': '0 0 0 1px rgba(0, 0, 0, 0.04)',
        sm: '0 1px 6px rgba(0, 0, 0, 0.04), 0 0 24px rgba(0, 0, 0, 0.05)',
        card: '0 1px 6px rgba(0, 0, 0, 0.04), 0 0 24px rgba(0, 0, 0, 0.05)',
        lg: '0 0 24px rgba(0, 0, 0, 0.15)',
      },
    },
  },
  plugins: [],
};
