import type { AuthState } from './types';

export const initialState: AuthState = {
  user: null,
  isAuthenticated: false,
  accessToken: null,
  refreshToken: null,
  lastActivityAt: null,
  tokenIssuedAt: null,
  tokenExpiresAt: null,
  hasCompletedOnboarding: false,
  onboardingStatus: null,
  currentOnboardingStep: null,
  pendingVerificationEmail: null,
  pendingVerificationMode: null,
  _pendingPasscode: null,
  hasPasscode: false,
  isBiometricEnabled: true,
  passcodeSessionToken: undefined,
  passcodeSessionExpiresAt: undefined,
  appLockExpiresAt: undefined,
  loginAttempts: 0,
  lockoutUntil: null,
  isLoading: false,
  error: null,
  registrationData: {
    firstName: '',
    lastName: '',
    dob: '',
    street: '',
    city: '',
    state: '',
    postalCode: '',
    country: '',
    phone: '',
    password: '',
    authMethod: 'password',
    firstJob: null,
    verifyCardDismissed: false,
  },
};
