import React from 'react';
import { View, Text, Pressable, ScrollView } from 'react-native';
import BottomSheet, { BottomSheetBackdrop } from '@gorhom/bottom-sheet';
import { HugeiconsIcon } from '@hugeicons/react-native';
import {
  InformationCircleIcon,
  ArrowUpRight01Icon,
  Flag01Icon,
  CustomerServiceIcon,
  Cancel01Icon,
} from '@hugeicons/core-free-icons';
import type { DataSource } from '@/utils/aiTrust';
import { formatTimestampFreshness } from '@/utils/aiTrust';

interface Props {
  visible: boolean;
  onClose: () => void;
  sources: DataSource[];
  modelVersion?: string;
  onReport?: () => void;
  onEscalate?: () => void;
}

export function DataSourceSheet({
  visible,
  onClose,
  sources,
  modelVersion,
  onReport,
  onEscalate,
}: Props) {
  const sheetRef = React.useRef<BottomSheet>(null);

  React.useEffect(() => {
    // Defer snap to avoid state updates before BottomSheet mounts
    const timeout = setTimeout(() => {
      if (visible) sheetRef.current?.snapToIndex(0);
      else sheetRef.current?.close();
    }, 50);
    return () => clearTimeout(timeout);
  }, [visible]);

  return (
    <BottomSheet
      ref={sheetRef}
      index={-1}
      snapPoints={['60%']}
      enablePanDownToClose
      backdropComponent={(props) => (
        <BottomSheetBackdrop {...props} disappearsOnIndex={-1} appearsOnIndex={0} />
      )}
      onClose={onClose}
      backgroundStyle={{ backgroundColor: '#FFFFFF' }}
      handleStyle={{ backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20 }}
      handleIndicatorStyle={{ backgroundColor: '#B5B5B5', width: 36, height: 4, borderRadius: 2 }}>
      <View className="flex-1">
        {/* Header */}
        <View className="flex-row items-center justify-between px-5 pt-2 pb-4">
          <View className="flex-row items-center gap-2">
            <HugeiconsIcon icon={InformationCircleIcon} size={20} color="#FF2E01" />
            <Text className="font-heading-semibold text-lg text-text-primary">Data Sources</Text>
          </View>
          <Pressable
            onPress={onClose}
            className="w-8 h-8 rounded-full bg-black/[0.06] items-center justify-center"
            accessibilityRole="button"
            accessibilityLabel="Close data sources">
            <HugeiconsIcon icon={Cancel01Icon} size={16} color="#8C8C8C" />
          </Pressable>
        </View>

        <ScrollView className="flex-1 px-5" showsVerticalScrollIndicator={false}>
          {/* Model info */}
          {modelVersion && (
            <View className="bg-gray-50 rounded-xl p-3 mb-4">
              <Text className="font-body-medium text-xs text-text-secondary">
                Generated by {modelVersion}
              </Text>
            </View>
          )}

          {/* Sources list */}
          {sources.length === 0 ? (
            <View className="items-center py-8">
              <Text className="font-body text-sm text-text-tertiary">
                No external data sources for this insight
              </Text>
            </View>
          ) : (
            <View className="gap-3">
              {sources.map((source, i) => (
                <View key={i} className="bg-white rounded-xl border border-black/[0.06] p-3.5">
                  <View className="flex-row items-start justify-between">
                    <Text className="font-body-medium text-sm text-text-primary flex-1 mr-2">
                      {source.name}
                    </Text>
                  </View>
                  <Text className="font-body text-xs text-text-tertiary mt-1">
                    {source.type} · {formatTimestampFreshness(source.lastSyncedAt)}
                  </Text>
                </View>
              ))}
            </View>
          )}

          {/* Actions */}
          <View className="mt-6 gap-3 pb-8">
            <Pressable
              onPress={onReport}
              className="flex-row items-center gap-3 rounded-xl border border-black/[0.08] p-4"
              accessibilityRole="button"
              accessibilityLabel="Report incorrect data">
              <HugeiconsIcon icon={Flag01Icon} size={20} color="#8C8C8C" />
              <Text className="font-body-medium text-sm text-text-primary">Report incorrect data</Text>
            </Pressable>
            <Pressable
              onPress={onEscalate}
              className="flex-row items-center gap-3 rounded-xl border border-black/[0.08] p-4"
              accessibilityRole="button"
              accessibilityLabel="Ask a human to review">
              <HugeiconsIcon icon={CustomerServiceIcon} size={20} color="#8C8C8C" />
              <Text className="font-body-medium text-sm text-text-primary">Ask a human to review</Text>
            </Pressable>
          </View>
        </ScrollView>
      </View>
    </BottomSheet>
  );
}
