import React from 'react';
import { View, Text, Pressable, ScrollView } from 'react-native';
import BottomSheet, { BottomSheetBackdrop } from '@gorhom/bottom-sheet';
import { IconComponent as HugeiconsIcon } from '@/lib/icons';
import {
  InformationCircleIcon,
  ArrowUpRight01Icon,
  Flag01Icon,
  CustomerServiceIcon,
  Cancel01Icon,
} from '@/lib/icons';
import type { DataSource } from '@/utils/aiTrust';
import { formatTimestampFreshness } from '@/utils/aiTrust';

interface Props {
  visible: boolean;
  onClose: () => void;
  sources: DataSource[];
  modelVersion?: string;
  onReport?: () => void;
  onEscalate?: () => void;
}

export function DataSourceSheet({
  visible,
  onClose,
  sources,
  modelVersion,
  onReport,
  onEscalate,
}: Props) {
  const sheetRef = React.useRef<BottomSheet>(null);

  React.useEffect(() => {
    // Defer snap to avoid state updates before BottomSheet mounts
    const timeout = setTimeout(() => {
      if (visible) sheetRef.current?.snapToIndex(0);
      else sheetRef.current?.close();
    }, 50);
    return () => clearTimeout(timeout);
  }, [visible]);

  return (
    <BottomSheet
      ref={sheetRef}
      index={-1}
      snapPoints={['60%']}
      enablePanDownToClose
      backdropComponent={(props) => (
        <BottomSheetBackdrop {...props} disappearsOnIndex={-1} appearsOnIndex={0} />
      )}
      onClose={onClose}
      backgroundStyle={{ backgroundColor: '#FFFFFF' }}
      handleStyle={{
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
      }}
      handleIndicatorStyle={{ backgroundColor: '#B5B5B5', width: 36, height: 4, borderRadius: 2 }}>
      <View className="flex-1">
        {/* Header */}
        <View className="flex-row items-center justify-between px-5 pb-4 pt-2">
          <View className="flex-row items-center gap-2">
            <HugeiconsIcon icon={InformationCircleIcon} size={20} color="#ff3e00" />
            <Text className="font-heading-semibold text-lg text-text-primary">Data Sources</Text>
          </View>
          <Pressable
            onPress={onClose}
            className="h-8 w-8 items-center justify-center rounded-full bg-black/[0.06]"
            accessibilityRole="button"
            accessibilityLabel="Close data sources">
            <HugeiconsIcon icon={Cancel01Icon} size={16} color="#8C8C8C" />
          </Pressable>
        </View>

        <ScrollView className="flex-1 px-5" showsVerticalScrollIndicator={false}>
          {/* Model info */}
          {modelVersion && (
            <View className="mb-4 rounded-lg bg-stone-surface p-3">
              <Text className="font-body-medium text-xs text-text-secondary">
                Generated by {modelVersion}
              </Text>
            </View>
          )}

          {/* Sources list */}
          {sources.length === 0 ? (
            <View className="items-center py-8">
              <Text className="font-body text-sm text-text-tertiary">
                No external data sources for this insight
              </Text>
            </View>
          ) : (
            <View className="gap-3">
              {sources.map((source, i) => (
                <View
                  key={i}
                  className="rounded-lg border border-black/[0.06] bg-parchment-card p-3.5">
                  <View className="flex-row items-start justify-between">
                    <Text className="mr-2 flex-1 font-body-medium text-sm text-text-primary">
                      {source.name}
                    </Text>
                  </View>
                  <Text className="mt-1 font-body text-xs text-text-tertiary">
                    {source.type} · {formatTimestampFreshness(source.lastSyncedAt)}
                  </Text>
                </View>
              ))}
            </View>
          )}

          {/* Actions */}
          <View className="mt-6 gap-3 pb-8">
            <Pressable
              onPress={onReport}
              className="flex-row items-center gap-3 rounded-lg border border-black/[0.08] p-4"
              accessibilityRole="button"
              accessibilityLabel="Report incorrect data">
              <HugeiconsIcon icon={Flag01Icon} size={20} color="#8C8C8C" />
              <Text className="font-body-medium text-sm text-text-primary">
                Report incorrect data
              </Text>
            </Pressable>
            <Pressable
              onPress={onEscalate}
              className="flex-row items-center gap-3 rounded-lg border border-black/[0.08] p-4"
              accessibilityRole="button"
              accessibilityLabel="Ask a human to review">
              <HugeiconsIcon icon={CustomerServiceIcon} size={20} color="#8C8C8C" />
              <Text className="font-body-medium text-sm text-text-primary">
                Ask a human to review
              </Text>
            </Pressable>
          </View>
        </ScrollView>
      </View>
    </BottomSheet>
  );
}
